[project]
name = "python-template"
version = "0.1.0"
description = "UV configuration containing the necessary librairies to run the python template."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cookiecutter>=2.6.0",
]
