name: cicd
concurrency: 
  group: cicd
  cancel-in-progress: false

on:
  push:

jobs:
  test-template:
    runs-on: ubuntu-latest
    env:
      TEST_PROJECT_DIR: rootpkg
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: install cookiecutter
        run: |
          uv venv
          uv pip install cookiecutter
        
      - name: create-test-project
        run: |
          make TEST_PROJECT_DIR=${{ env.TEST_PROJECT_DIR }} \
            create-tmp-project create-tmp-project