name: release
concurrency: 
  group: release-${{ github }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.3.x'

      - name: Determine Version
        id: versioning
        uses: gittools/actions/gitversion/execute@v4
        with:
          configFilePath: GitVersion.yml

      - name: Tag commit
        uses: actions/github-script@v8
        env:
          TAG_NAME: ${{ steps.versioning.outputs.FullsemVer }}
        with:
          script: |
            const script = require('./scripts/js/tag_commit.js')
            console.log(script({github, context}))
      
      - name: create release
        uses: actions/create-release@v1
        with: 
          tag_name: ${{ steps.versioning.outputs.fullSemVer }}
          body: ${{ github.event.pull_request.body }}
          release_name: Release ${{ steps.versioning.outputs.fullSemVer }} - ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false
          


